### ISSUE TITLE
Vor- und Nachteile von Autosave

### ISSUE THREAD

**Issue by lukasrad02** [dasGoogle/sommercamp-2021-templates#1]
Ich frage mich, ob die VS-Code Einstellungen so, wie sie aktuell sind, sinnvoll sind. Beim P5-Camp ist mir aufgefallen, dass es teilweise durch das Autosave zu Problemen kam, weil der LiveServer Seiten automatisch neulädt, wenn sich der Code ändert. Dadurch durfte niemand in den Dateien schreiben, wenn gerade eine andere Person die Seite betrachten wollte, weil das ständige Neuladen die Seite sonst praktisch unbenutzbar gemacht hat.

Ohne Autosave gibt es natürlich das Problem, dass nur die Person, die den LiveShare hostet, speichern kann, die anderen Leute aus dem Team also zum Testen immer von dieser Person abhängen. Autosave auszuschalten ist also auch nicht zielführend.

Die Lösung, die ich bisher gefunden habe, ist, die Liste der für das Reloading zu ignorierender Dateien (`liveServer.settings.ignoreFiles`) auf ein Wildcard zu setzen, um somit das automatiche Reloading komplett auszuschalten. Allerdings werden wir dann wahrscheinlich alle paar Minuten zu Gruppen gehen, bei denen der neu eingefügte Code scheinbar nicht funktioniert, weil sie nicht neu geladen haben...

Was würdet ihr zu diesem Problem sagen und welche Lösung haltet ihr für die sinnvollste?

**Comment by dasGoogle** [comment]
Ich denke, hier ist es am vertretbarsten, wenn wir tatsächlich dem Liveserver das Hot Reload verbieten. Zumindest ab dem Moment, wo wir mit JavaScript arbeiten. Bis dahin ist es wahrscheinlich ziemlich praktisch, wenn sich die Sachen von selbst updaten.

**Comment by lukasrad02** [comment]
Wenn würde ich es glaube ich konsistent machen, sonst vergessen vermutlich noch mehr Gruppen, dass sie die Seite plötzlich neu laden müssen

**Comment by dasGoogle** [comment]
Stimmt. Dann passe ich das mal an.
